### ISSUE TITLE
可以根据官方内测的翻译来弄

### ISSUE THREAD

**Issue by tangjyan** [nancheung97/notion-zh_CN#9]
https://www.notion.so/index-zh-CN-6a31bd9c1dbf896f2bc4.html

**Comment by nancheung** [comment]
v0.2.0使用了官翻，但是官翻内容太多，出现了 #8 的问题，就先回滚回去了，后续看看怎么优化这个问题

**Comment by tangjyan** [comment]
我测试了一下，直接安装确实不起作用，但是安装之前的版本，然后把官翻的内容复制粘贴到老板的格式内容中，是可以使用的，我感觉是不是哪个代码写错了。
![image](https://user-images.githubusercontent.com/21167731/129328864-20f36487-6049-4778-ad4f-03ffbb136fb1.png)
